# Generated by Django 4.2.7 on 2024-04-27 18:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FitFeverApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('grupo_muscular', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Perder Peso', 'Perder Peso'), ('Ganar Masa Muscular', 'Ganar Masa Muscular'), ('Mantener Peso', 'Mantener Peso')], max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('factor_Actividad', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)])),
                ('foto_perfil', models.ImageField(default='FitFeverApp/static/perfil_imagenes/default.jpg', upload_to='FitFeverApp/static/perfil_imagenes/')),
                ('fecha_nacimiento', models.DateField()),
                ('Calorias', models.FloatField()),
                ('Objetivo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.objetivo')),
                ('id_perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('Objetivo', models.CharField(choices=[('Perder Peso', 'Perder Peso'), ('Ganar Masa Muscular', 'Ganar Masa Muscular'), ('Mantener Peso', 'Mantener Peso')], max_length=50)),
                ('duracion', models.IntegerField()),
                ('nivel', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.perfiles')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='id_rutina',
            field=models.ManyToManyField(to='FitFeverApp.rutinas'),
        ),
    ]
