# Generated by Django 4.2.7 on 2024-04-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0002_ejercicios_objetivo_perfiles_rutinas_delete_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercicios',
            old_name='id_rutina',
            new_name='rutina',
        ),
        migrations.RenameField(
            model_name='objetivo',
            old_name='id_objetivo',
            new_name='objetivo',
        ),
        migrations.RenameField(
            model_name='perfiles',
            old_name='Objetivo_id',
            new_name='Objetivo',
        ),
        migrations.RenameField(
            model_name='rutinas',
            old_name='id_perfil',
            new_name='perfil',
        ),
    ]
