# Generated by Django 4.2.7 on 2024-04-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0003_rename_id_rutina_ejercicios_rutina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('calorias', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('grasas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('ingredientes', models.CharField(max_length=200)),
                ('Objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calorias', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('grasas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('id_producto', models.ManyToManyField(to='FitFeverApp.recetas')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Momento_dia', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Comida', 'Comida'), ('Merienda', 'Merienda'), ('Cena', 'Cena')], max_length=50)),
                ('calorias', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('grasas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('id_detalle', models.ManyToManyField(to='FitFeverApp.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consumo', models.DateField()),
                ('calorias_consumidas', models.FloatField()),
                ('calorias_restantes', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('grasas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('momento_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.detail_consumo')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.objetivo')),
            ],
        ),
    ]
