# Generated by Django 4.2.7 on 2024-04-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0004_recetas_productos_detail_consumo_consumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfiles',
            old_name='id_perfil',
            new_name='perfil',
        ),
    ]
