# Generated by Django 4.2.7 on 2024-05-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0007_alter_perfiles_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='foto_perfil',
            field=models.CharField(max_length=200),
        ),
    ]
