# Generated by Django 4.2.7 on 2024-05-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0008_alter_perfiles_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='calorias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='carbohidratos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='grasas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='proteinas',
            field=models.CharField(max_length=50),
        ),
    ]
