# Generated by Django 4.2.7 on 2024-05-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0009_alter_productos_calorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.perfiles'),
        ),
    ]
