# Generated by Django 4.2.7 on 2024-05-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0010_consumo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.perfiles'),
        ),
    ]
