# Generated by Django 4.2.7 on 2024-05-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0011_recetas_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivo',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='fecha_inicio',
        ),
    ]
