# Generated by Django 4.2.7 on 2024-05-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0012_remove_objetivo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='perfil',
        ),
    ]
