# Generated by Django 4.2.7 on 2024-05-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0013_remove_consumo_objetivo_remove_recetas_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='recetas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.recetas'),
        ),
    ]
