# Generated by Django 4.2.7 on 2024-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0014_consumo_recetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_consumo',
            name='calorias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail_consumo',
            name='carbohidratos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail_consumo',
            name='grasas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail_consumo',
            name='proteinas',
            field=models.CharField(max_length=50),
        ),
    ]
