# Generated by Django 4.2.7 on 2024-05-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0015_alter_detail_consumo_calorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='calorias_consumidas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='calorias_restantes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='carbohidratos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='grasas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='proteinas',
            field=models.CharField(max_length=50),
        ),
    ]
