# Generated by Django 4.2.7 on 2024-05-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0016_alter_consumo_calorias_consumidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailConsumoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias', models.CharField(max_length=50)),
                ('proteinas', models.CharField(max_length=50)),
                ('grasas', models.CharField(max_length=50)),
                ('carbohidratos', models.CharField(max_length=50)),
                ('detail_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.detail_consumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.productos')),
            ],
        ),
    ]
