# Generated by Django 4.2.7 on 2024-05-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0017_detailconsumoproducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailConsumoProducto',
            new_name='Detail_Consumo_Producto',
        ),
    ]
