# Generated by Django 4.2.7 on 2024-05-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0018_rename_detailconsumoproducto_detail_consumo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_consumo',
            name='id_detalle',
        ),
    ]
