# Generated by Django 4.2.7 on 2024-05-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0019_remove_detail_consumo_id_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='recetas',
            name='calorias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='carbohidratos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='grasas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='proteinas',
            field=models.CharField(max_length=50),
        ),
    ]
