# Generated by Django 4.2.7 on 2024-05-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0020_remove_recetas_descripcion_alter_recetas_calorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
