# Generated by Django 4.2.7 on 2024-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0021_recetas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='instrucciones',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
