# Generated by Django 4.2.7 on 2024-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0022_recetas_instrucciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='calorias',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productos',
            name='carbohidratos',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productos',
            name='grasas',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productos',
            name='proteinas',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='calorias',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='carbohidratos',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='grasas',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='imagen',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='ingredientes',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='nombre',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='proteinas',
            field=models.CharField(max_length=2500),
        ),
    ]
