# Generated by Django 4.2.7 on 2024-06-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0024_ejercicios_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinas',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
