# Generated by Django 4.2.7 on 2024-06-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0025_rutinas_dia_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinasAsociadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=50)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.perfiles')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitFeverApp.rutinas')),
            ],
        ),
    ]
