# Generated by Django 4.2.7 on 2024-06-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0026_rutinasasociadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinasasociadas',
            name='fecha_asociada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
