# Generated by Django 4.2.7 on 2024-06-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFeverApp', '0027_rutinasasociadas_fecha_asociada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='carbohidratos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='grasas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='proteinas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
